### ISSUE TITLE
Interpretation of uv_raw

### ISSUE THREAD

**Issue by Bra1nsen** [adafruit/Adafruit_CircuitPython_VEML6070#23]
Sorry but i cant find any information about how to interpret the measured values - what exactly tells me the value of uv_raw?
I know wavelength range is about 310-420nm. If my veml6070 sensor shows up with uv_raw = 2, what does this mean?

Thank you!

**Comment by tekktrik** [comment]
It's essentially a raw value, like an ADC value, that gets translated to a UV index depending on the integration time that is set.  Because it depends on the integration time, I don't know if it represents a concrete value so much as a means to calculate that UV index.  Here's a table from the application note for the sensor for reference:

![IntegrationTime2](https://user-images.githubusercontent.com/89490472/155363031-b40fdc17-518c-4fc7-a458-e8af8fed39fd.PNG)
